CREATE TABLE "User" (
    id UUID PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password VARCHAR(64) NOT NULL,
    salt VARCHAR(100) NOT NULL,
    createdAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    isActive BOOLEAN DEFAULT TRUE
);
