CREATE TABLE "UserRole" (
    "name" VARCHAR(256) NOT NULL PRIMARY KEY,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" BOOLEAN DEFAULT FALSE
);

INSERT INTO "UserRole" ("name") VALUES ('ADMIN');

CREATE TABLE "User" (
    "id" UUID PRIMARY KEY,
    "email" VARCHAR(320) NOT NULL,
    "password" VARCHAR(64) NOT NULL,
    "salt" VARCHAR(100) NOT NULL,
    "role" VARCHAR(256) NOT NULL REFERENCES "UserRole"("name"),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isActive" BOOLEAN DEFAULT TRUE
);

CREATE TABLE "Privilege" (
    "name" VARCHAR(256) NOT NULL PRIMARY KEY,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "UserRolePrivilegeMap" (
    "userRole" VARCHAR(256) NOT NULL,
    "privilege" VARCHAR(256) NOT NULL,
    PRIMARY KEY ("userRole", "privilege"),
    FOREIGN KEY ("userRole") REFERENCES "UserRole"("name"),
    FOREIGN KEY ("privilege") REFERENCES "Privilege"("name")
);

CREATE TABLE "WebToken" (
    "token" UUID PRIMARY KEY,
    "userId" UUID NOT NULL REFERENCES "User"("id"),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "isDeleted" BOOLEAN DEFAULT FALSE
);
