CREATE TABLE "Note" (
    "id" UUID PRIMARY KEY,
    "title" VARCHAR(500) NOT NULL,
    "description" VARCHAR(2000),
    "createdBy" UUID NOT NULL REFERENCES "User"("id"),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" BOOLEAN DEFAULT FALSE
);
